version: '3.8'

services:
  web:
    build: ./paritetdent
    restart: always
    container_name: paritetdent
    command: gunicorn paritetdent.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - ./paritetdent:/home/app
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    volumes:
      - ./paritetdent/robots.txt:/home/app/robots.txt
      - ./paritetdent/static:/home/app/static
      - ./paritetdent/media:/home/app/media
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
