# Generated by Django 3.0.4 on 2020-05-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресение')], max_length=9, unique=True, verbose_name='День недели')),
                ('opening_hours', models.TimeField(verbose_name='Время открытия')),
                ('closing_hours', models.TimeField(verbose_name='Время закрытия')),
            ],
            options={
                'verbose_name': 'Часы работы',
            },
        ),
    ]
