# Generated by Django 3.0.4 on 2020-05-06 13:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Авто-заполняемое поле, руками не трогать! :)', unique=True)),
                ('text', ckeditor.fields.RichTextField(max_length=512, unique=True, verbose_name='Название')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положения',
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Часы работы', 'verbose_name_plural': 'Часы работы'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_hours',
            field=models.TimeField(default='21:00:00', verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_hours',
            field=models.TimeField(default='09:00:00', verbose_name='Время открытия'),
        ),
    ]
