# Generated by Django 3.0.4 on 2020-05-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200506_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regulations',
            new_name='Regulation',
        ),
    ]
