# Generated by Django 3.0.4 on 2020-05-10 00:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200506_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='text',
            field=ckeditor.fields.RichTextField(unique=True, verbose_name='Название'),
        ),
    ]
