# Generated by Django 3.0.4 on 2020-05-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200512_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule',
            new_name='day',
        ),
    ]
