# Generated by Django 3.0.4 on 2020-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200517_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='Название')),
                ('image', models.FileField(blank=True, null=True, upload_to='licenses', verbose_name='Изображение')),
            ],
        ),
    ]
