# Generated by Django 3.0.4 on 2020-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Файл лицензии', 'verbose_name_plural': 'Файлы лицензии'},
        ),
        migrations.AlterField(
            model_name='license',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='license', verbose_name='Изображение'),
        ),
    ]
