# Generated by Django 3.0.4 on 2020-05-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200517_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_off',
            field=models.BooleanField(default=0, verbose_name='Выходной'),
        ),
    ]
