# Generated by Django 3.0.4 on 2020-04-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256, unique=True, verbose_name='Должность')),
                ('slug', models.SlugField(help_text='Авто-заполняемое поле, руками не трогать! :)', unique=True)),
                ('schedule', models.CharField(choices=[('П', 'Полный рабочий день'), ('У', 'Удаленная работа'), ('Г', 'Гибкий график'), ('С', 'Сменный график')], max_length=1, verbose_name='График работы')),
                ('experience', models.CharField(help_text='Пример: от 2 до 3 лет', max_length=128, verbose_name='Опыт')),
                ('salary', models.CharField(help_text='Пример: от 2.000 рублей в месяц', max_length=128, verbose_name='Заработная плата')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('conditions', models.TextField(verbose_name='Условия работы')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
