# Generated by Django 3.0.4 on 2020-05-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200515_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Отклик на вакансию', 'verbose_name_plural': 'Отклики на вакансии'},
        ),
    ]
