# Generated by Django 3.0.4 on 2020-04-01 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20200401_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='lastname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='firstname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='workers',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата добавления сотрудника', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
