# Generated by Django 3.0.4 on 2020-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20200401_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
    ]
