# Generated by Django 3.0.4 on 2020-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20200401_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='position',
        ),
        migrations.AddField(
            model_name='workers',
            name='position',
            field=models.ManyToManyField(to='workers.Positions', verbose_name='Должность'),
        ),
    ]
