# Generated by Django 3.0.4 on 2020-05-05 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Цена услуги', 'verbose_name_plural': 'Цены услуг'},
        ),
        migrations.AddField(
            model_name='pricelist',
            name='modified_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата последнего изменения'),
            preserve_default=False,
        ),
    ]
