# Generated by Django 3.0.4 on 2020-05-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='base',
        ),
        migrations.AddField(
            model_name='sales',
            name='constantly',
            field=models.BooleanField(default=0, verbose_name='Действует постоянно'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='draft',
            field=models.BooleanField(default=0, verbose_name='Опубликовано'),
        ),
    ]
