# Generated by Django 3.0.4 on 2020-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='text',
        ),
        migrations.AddField(
            model_name='classification',
            name='image',
            field=models.ImageField(default=0, upload_to='classification/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
