# Generated by Django 3.0.4 on 2020-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200511_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='image',
            field=models.FileField(help_text='Только SVG формат', upload_to='classification/', verbose_name='Изображение'),
        ),
    ]
