# Generated by Django 3.0.4 on 2020-05-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200511_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='classifications', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Classification', verbose_name='Классификация услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
