# Generated by Django 3.0.4 on 2020-05-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200512_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='order',
            field=models.FloatField(default=1, max_length=24, verbose_name='Номер по порядку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Код услуги'),
        ),
    ]
