# Generated by Django 3.0.4 on 2020-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20200512_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.FloatField(help_text='Цена услуги в рублях', verbose_name='Цена'),
        ),
    ]
