# Generated by Django 3.0.4 on 2020-05-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20200512_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='order',
            field=models.CharField(max_length=24, verbose_name='Номер по порядку'),
        ),
    ]
