# Generated by Django 3.0.4 on 2020-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200512_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('call', models.BooleanField(default=0, verbose_name='Разговор состоялся')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
    ]
