# Generated by Django 3.0.4 on 2020-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Заявка на запись', 'verbose_name_plural': 'Заявки на запись'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='call',
            field=models.BooleanField(default=0, verbose_name='Диалог состоялся'),
        ),
    ]
