# Generated by Django 3.0.4 on 2020-05-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20200515_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='text',
            field=models.TextField(blank=True, max_length=512, verbose_name='Описание проблемы'),
        ),
    ]
